const MAP = {
  "Invisible Block": { locations: [{ x: 0, y: 0 }], category: "Misc", tags: ["utility", "hidden"] },
  "Big Normal Stone Bricks": { locations: [{ x: 16, y: 0 }], category: "Structure", tags: ["stone", "brick"] },
  "Big Normal Stone Bricks with Lianas": { locations: [{ x: 32, y: 0 }], category: "Structure", tags: ["stone", "brick", "Nature"] },
  "Big Normal Stone Bricks with Moss": { locations: [{ x: 48, y: 0 }], category: "Structure", tags: ["stone", "brick", "Nature"] },
  "Stone Block": { locations: [{ x: 64, y: 0 }], category: "Structure", tags: ["stone"] },
  "Stone": { locations: [{ x: 80, y: 0 }], category: "Structure", tags: ["stone"] },
  "Stone Bricks 2": { locations: [{ x: 96, y: 0 }], category: "Structure", tags: ["stone", "brick"] },
  "Worn Big Stone Bricks": { locations: [{ x: 112, y: 0 }], category: "Structure", tags: ["stone", "brick", "worn"] },
  "Cobblestone Path": { locations: [{ x: 128, y: 0 }], category: "Structure", tags: ["stone", "path"] },
  "Chiseled Stone": { locations: [{ x: 144, y: 0 }], category: "Structure", tags: ["stone", "chiseled"] },
  "Sandstone Block": { locations: [{ x: 160, y: 0 }, { x: 208, y: 0 }, { x: 224, y: 0 }], category: "Structure", tags: ["sandstone"] },
  "Big Sandstone Bricks": { locations: [{ x: 176, y: 0 }], category: "Structure", tags: ["sandstone", "brick"] },
  "Chiseled Sandstone": { locations: [{ x: 192, y: 0 }], category: "Structure", tags: ["sandstone", "chiseled"] },
  "White Small Bricks": { locations: [{ x: 0, y: 48 }], category: "Structure", tags: ["brick", "white"] },
  "Old Temple Bricks": { locations: [{ x: 192, y: 48 }], category: "Structure", tags: ["temple", "brick"] },
  "Old Temple Decoration": { locations: [{ x: 208, y: 48 }], category: "Structure", tags: ["temple", "deco"] },
  "Quartz Chiseled Block": { locations: [{ x: 240, y: 48 }], category: "Structure", tags: ["quartz", "chiseled"] },
  "Quartz Pillar Side": { locations: [{ x: 256, y: 48 }], category: "Structure", tags: ["quartz", "pillar"] },
  "Quartz Pillar Top": { locations: [{ x: 272, y: 48 }, { x: 288, y: 48 }], category: "Structure", tags: ["quartz", "pillar"] },
  "Quartz Tiles": { locations: [{ x: 304, y: 48 }], category: "Structure", tags: ["quartz", "tile"] },
  "Mud Bricks": { locations: [{ x: 0, y: 64 }], category: "Structure", tags: ["mud", "brick"] },
  "Eroded Bricks Blue": { locations: [{ x: 48, y: 64 }], category: "Structure", tags: ["brick", "blue", "worn"] },
  "Red Bricks Medium": { locations: [{ x: 64, y: 64 }], category: "Structure", tags: ["brick", "red"] },
  "Green Tiles": { locations: [{ x: 80, y: 64 }], category: "Structure", tags: ["tile", "green"] },
  "Purple Floor Tile": { locations: [{ x: 144, y: 48 }], category: "Structure", tags: ["tile", "purple"] },
  "Big Normal Stone Bricks Fractured": { locations: [{ x: 80, y: 80 }], category: "Structure", tags: ["stone", "brick", "fractured"] },
  "Big Normal Stone Bricks Variant": { locations: [{ x: 192, y: 80 }], category: "Structure", tags: ["stone", "brick"] },
  "Blue Tile": { locations: [{ x: 208, y: 80 }], category: "Structure", tags: ["tile", "blue"] },

  "Grassy Dirt Side": { locations: [{ x: 240, y: 0 }], category: "Nature", tags: ["grass", "dirt"] },
  "Grass Block": { locations: [{ x: 256, y: 0 }], category: "Nature", tags: ["grass"] },
  "Dirt": { locations: [{ x: 272, y: 0 }], category: "Nature", tags: ["dirt"] },
  "Grassy Dirt Side Slab": { locations: [{ x: 288, y: 0 }], category: "Nature", tags: ["grass", "slab"] },
  "Sand": { locations: [{ x: 304, y: 0 }], category: "Nature", tags: ["sand"] },
  "Moss": { locations: [{ x: 352, y: 16 }], category: "Nature", tags: ["moss"] },
  "Snow": { locations: [{ x: 448, y: 32 }], category: "Nature", tags: ["snow"] },
  "Ice Block": { locations: [{ x: 144, y: 64 }], category: "Nature", tags: ["ice"] },
  "Mud Block": { locations: [{ x: 16, y: 64 }], category: "Nature", tags: ["mud"] },
  "Mud": { locations: [{ x: 32, y: 64 }], category: "Nature", tags: ["mud"] },
  "Grass": { locations: [{ x: 96, y: 80 }], category: "Nature", tags: ["grass"] },
  "Grass I": { locations: [{ x: 224, y: 80 }], category: "Nature", tags: ["grass"] },
  "Grass II": { locations: [{ x: 240, y: 80 }], category: "Nature", tags: ["grass"] },
  "Old Temple Gravel": { locations: [{ x: 224, y: 48 }], category: "Nature", tags: ["gravel"] },

  "Foliage 1": { locations: [{ x: 288, y: 16 }], category: "Nature", tags: ["plant", "leaf"] },
  "Foliage 1 with Purple Flowers": { locations: [{ x: 304, y: 16 }], category: "Nature", tags: ["plant", "flower"] },
  "Lavender": { locations: [{ x: 320, y: 16 }], category: "Nature", tags: ["plant", "flower"] },
  "Lianas": { locations: [{ x: 336, y: 16 }], category: "Nature", tags: ["plant", "liana"] },
  "Yellow Flowers": { locations: [{ x: 368, y: 16 }], category: "Nature", tags: ["plant", "flower"] },
  "Foliage 2": { locations: [{ x: 384, y: 16 }], category: "Nature", tags: ["plant", "leaf"] },
  "Fly Agaric": { locations: [{ x: 400, y: 16 }], category: "Nature", tags: ["plant", "mushroom"] },
  "Bamboo Lower": { locations: [{ x: 272, y: 16 }], category: "Nature", tags: ["plant", "bamboo"] },
  "Blue Flowers": { locations: [{ x: 112, y: 80 }], category: "Nature", tags: ["plant", "flower"] },
  "Sunflower": { locations: [{ x: 128, y: 80 }], category: "Nature", tags: ["plant", "flower"] },
  "Sunflower Stem": { locations: [{ x: 144, y: 80 }], category: "Nature", tags: ["plant"] },
  "Sunflower Stem (Without Leaves)": { locations: [{ x: 160, y: 80 }], category: "Nature", tags: ["plant"] },

  "Oak Log Side": { locations: [{ x: 320, y: 0 }], category: "Wood", tags: ["oak", "log"] },
  "Oak Log Top": { locations: [{ x: 336, y: 0 }, { x: 352, y: 0 }], category: "Wood", tags: ["oak", "log"] },
  "Oak Planks": { locations: [{ x: 368, y: 0 }, { x: 432, y: 0 }, { x: 448, y: 0 }], category: "Wood", tags: ["oak", "plank"] },
  "Oak Door Bottom": { locations: [{ x: 384, y: 0 }], category: "Wood", tags: ["oak", "door"] },
  "Oak Door Top": { locations: [{ x: 400, y: 0 }], category: "Wood", tags: ["oak", "door"] },
  "Oak Bookshelf": { locations: [{ x: 416, y: 0 }], category: "Wood", tags: ["oak", "bookshelf"] },
  "Oak Fence": { locations: [{ x: 464, y: 0 }], category: "Wood", tags: ["oak", "fence"] },
  "Dark Oak Log Side": { locations: [{ x: 480, y: 0 }], category: "Wood", tags: ["dark_oak", "log"] },
  "Dark Oak Log Top": { locations: [{ x: 496, y: 0 }, { x: 0, y: 16 }], category: "Wood", tags: ["dark_oak", "log"] },
  "Dark Oak Planks": { locations: [{ x: 16, y: 16 }, { x: 96, y: 16 }, { x: 112, y: 16 }], category: "Wood", tags: ["dark_oak", "plank"] },
  "Dark Oak Stump": { locations: [{ x: 32, y: 16 }], category: "Wood", tags: ["dark_oak", "log"] },
  "Dark Oak Stump Top": { locations: [{ x: 48, y: 16 }, { x: 64, y: 16 }], category: "Wood", tags: ["dark_oak", "log"] },
  "Dark Oak Bookshelf": { locations: [{ x: 80, y: 16 }], category: "Wood", tags: ["dark_oak", "bookshelf"] },
  "Magic Wood Log Side": { locations: [{ x: 464, y: 48 }], category: "Wood", tags: ["magic", "log"] },
  "Magic Wood Log": { locations: [{ x: 480, y: 48 }, { x: 496, y: 48 }], category: "Wood", tags: ["magic", "log"] },
  "Magic Wood Planks": { locations: [{ x: 384, y: 48 }, { x: 400, y: 48 }], category: "Wood", tags: ["magic", "plank"] },
  "Magic Wood Door Bottom": { locations: [{ x: 416, y: 48 }], category: "Wood", tags: ["magic", "door"] },
  "Magic Wood Door Top": { locations: [{ x: 432, y: 48 }], category: "Wood", tags: ["magic", "door"] },
  "Magic Wood Fence": { locations: [{ x: 448, y: 48 }], category: "Wood", tags: ["magic", "fence"] },
  "Magic Wood Bookshelf": { locations: [{ x: 368, y: 48 }], category: "Wood", tags: ["magic", "bookshelf"] },

  "Server Rack": { locations: [{ x: 240, y: 32 }], category: "Tech", tags: ["server", "tech"] },
  "Server Rack Top": { locations: [{ x: 256, y: 32 }, { x: 272, y: 32 }], category: "Tech", tags: ["server", "tech"] },
  "Keypad": { locations: [{ x: 288, y: 32 }], category: "Tech", tags: ["keypad", "tech"] },
  "Computer Terminal": { locations: [{ x: 304, y: 32 }], category: "Tech", tags: ["computer", "tech"] },
  "Control Panel": { locations: [{ x: 320, y: 32 }], category: "Tech", tags: ["panel", "tech"] },
  "Bank Locker Front": { locations: [{ x: 192, y: 32 }], category: "Tech", tags: ["locker", "tech"] },
  "Bank Locker Side": { locations: [{ x: 208, y: 32 }, { x: 224, y: 32 }], category: "Tech", tags: ["locker", "tech"] },
  "Clock": { locations: [{ x: 256, y: 16 }], category: "Tech", tags: ["clock"] },
  "Target": { locations: [{ x: 192, y: 16 }], category: "Tech", tags: ["target"] },

  "Iron Block": { locations: [{ x: 464, y: 16 }], category: "Industrial", tags: ["metal", "iron"] },
  "Copper Block": { locations: [{ x: 320, y: 48 }], category: "Industrial", tags: ["metal", "copper"] },
  "Steel Block": { locations: [{ x: 176, y: 80 }], category: "Industrial", tags: ["metal", "steel"] },
  "Gold Block": { locations: [{ x: 128, y: 64 }], category: "Industrial", tags: ["metal", "gold"] },
  "Sheet Metal": { locations: [{ x: 112, y: 32 }], category: "Industrial", tags: ["metal", "sheet"] },
  "Sheet Metal — Rusty": { locations: [{ x: 96, y: 32 }], category: "Industrial", tags: ["metal", "sheet", "worn"] },
  "Red Sheet Metal": { locations: [{ x: 304, y: 80 }], category: "Industrial", tags: ["metal", "sheet", "red"] },
  "Green Sheet Metal": { locations: [{ x: 320, y: 80 }], category: "Industrial", tags: ["metal", "sheet", "green"] },
  "Blue Sheet Metal": { locations: [{ x: 336, y: 80 }], category: "Industrial", tags: ["metal", "sheet", "blue"] },
  "Metal Fence": { locations: [{ x: 32, y: 32 }], category: "Industrial", tags: ["fence", "metal"] },
  "Iron Fence": { locations: [{ x: 0, y: 32 }], category: "Industrial", tags: ["fence", "iron"] },
  "Steel Bars": { locations: [{ x: 48, y: 32 }], category: "Industrial", tags: ["bars", "steel"] },
  "Iron Bars": { locations: [{ x: 448, y: 16 }], category: "Industrial", tags: ["bars", "iron"] },
  "Iron Mesh Fence": { locations: [{ x: 16, y: 32 }], category: "Industrial", tags: ["fence", "iron"] },
  "Copper Grid": { locations: [{ x: 336, y: 48 }], category: "Industrial", tags: ["grid", "copper"] },
  "Steel Grid": { locations: [{ x: 176, y: 96 }], category: "Industrial", tags: ["grid", "steel"] },
  "Iron Grid": { locations: [{ x: 192, y: 96 }], category: "Industrial", tags: ["grid", "iron"] },
  "Black Grid": { locations: [{ x: 160, y: 96 }], category: "Industrial", tags: ["grid", "black"] },
  "Ventilation Grate": { locations: [{ x: 416, y: 80 }], category: "Industrial", tags: ["grate", "vent"] },
  "Sewer Grate": { locations: [{ x: 272, y: 80 }], category: "Industrial", tags: ["grate", "sewer"] },
  "Manhole Cover": { locations: [{ x: 256, y: 80 }], category: "Industrial", tags: ["metal", "sewer"] },
  "Heavy Block": { locations: [{ x: 128, y: 32 }], category: "Industrial", tags: ["metal", "heavy"] },
  "Dark Asphalt": { locations: [{ x: 144, y: 32 }], category: "Industrial", tags: ["asphalt"] },
  "Non-Slip Surface": { locations: [{ x: 80, y: 32 }], category: "Industrial", tags: ["surface"] },
  "Non-Slip Surface 2": { locations: [{ x: 64, y: 32 }], category: "Industrial", tags: ["surface"] },

  "Light Block": { locations: [{ x: 96, y: 64 }], category: "Industrial", tags: ["light"] },
  "White Tube Light": { locations: [{ x: 416, y: 32 }], category: "Industrial", tags: ["light", "tube"] },
  "Tall White Tube Light Upper": { locations: [{ x: 384, y: 32 }], category: "Industrial", tags: ["light", "tube"] },
  "Tall White Tube Light Lower": { locations: [{ x: 400, y: 32 }], category: "Industrial", tags: ["light", "tube"] },
  "Green Yellow Red Lights": { locations: [{ x: 336, y: 32 }], category: "Industrial", tags: ["light", "signals"] },

  "Barrel Side": { locations: [{ x: 208, y: 16 }], category: "Industrial", tags: ["barrel", "wood"] },
  "Barrel Top": { locations: [{ x: 224, y: 16 }, { x: 240, y: 16 }], category: "Industrial", tags: ["barrel", "wood"] },
  "Barrel Small Side": { locations: [{ x: 432, y: 80 }], category: "Industrial", tags: ["barrel", "small"] },
  "Barrel Small Top": { locations: [{ x: 448, y: 80 }, { x: 464, y: 80 }], category: "Industrial", tags: ["barrel", "small"] },
  "Red Barrel": { locations: [{ x: 480, y: 80 }], category: "Industrial", tags: ["barrel", "metal", "red"] },
  "Red Barrel Top": { locations: [{ x: 496, y: 80 }], category: "Industrial", tags: ["barrel", "metal", "red"] },
  "Red Barrel Bottom": { locations: [{ x: 0, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "red"] },
  "Steel Barrel": { locations: [{ x: 16, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "steel"] },
  "Steel Barrel Top": { locations: [{ x: 32, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "steel"] },
  "Steel Barrel Bottom": { locations: [{ x: 48, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "steel"] },
  "Yellow Barrel": { locations: [{ x: 64, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "yellow"] },
  "Yellow Barrel Top": { locations: [{ x: 80, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "yellow"] },
  "Yellow Barrel Bottom": { locations: [{ x: 96, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "yellow"] },
  "Black Barrel": { locations: [{ x: 112, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "black"] },
  "Black Barrel Top": { locations: [{ x: 128, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "black"] },
  "Black Barrel Bottom": { locations: [{ x: 144, y: 96 }], category: "Industrial", tags: ["barrel", "metal", "black"] },
  "Cardboard Box Side": { locations: [{ x: 80, y: 48 }], category: "Misc", tags: ["box", "cardboard"] },
  "Cardboard Box Top": { locations: [{ x: 96, y: 48 }], category: "Misc", tags: ["box", "cardboard"] },
  "Cardboard Box Bottom": { locations: [{ x: 112, y: 48 }], category: "Misc", tags: ["box", "cardboard"] },
  "Cardboard Box Side1": { locations: [{ x: 128, y: 48 }], category: "Misc", tags: ["box", "cardboard"] },
  "Trash Can Side": { locations: [{ x: 352, y: 80 }], category: "Industrial", tags: ["trash", "metal"] },
  "Trash Can Top": { locations: [{ x: 368, y: 80 }], category: "Industrial", tags: ["trash", "metal"] },
  "Trash Can Bottom": { locations: [{ x: 384, y: 80 }], category: "Industrial", tags: ["trash", "metal"] },
  "Trash Can Side1": { locations: [{ x: 400, y: 80 }], category: "Industrial", tags: ["trash", "metal"] },

  "Prototype Grid: Black": { locations: [{ x: 352, y: 64 }], category: "Prototyping", tags: ["grid", "black"] },
  "Prototype Grid: Green": { locations: [{ x: 368, y: 64 }], category: "Prototyping", tags: ["grid", "green"] },
  "Prototype Grid: Purple": { locations: [{ x: 384, y: 64 }], category: "Prototyping", tags: ["grid", "purple"] },
  "Prototype Grid: Red": { locations: [{ x: 400, y: 64 }], category: "Prototyping", tags: ["grid", "red"] },
  "Prototype Grid: Yellow": { locations: [{ x: 416, y: 64 }], category: "Prototyping", tags: ["grid", "yellow"] },
  "Prototype Checks: Black": { locations: [{ x: 432, y: 64 }], category: "Prototyping", tags: ["checks", "black"] },
  "Prototype Checks: Green": { locations: [{ x: 448, y: 64 }], category: "Prototyping", tags: ["checks", "green"] },
  "Prototype Checks: Purple": { locations: [{ x: 464, y: 64 }], category: "Prototyping", tags: ["checks", "purple"] },
  "Prototype Checks: Red": { locations: [{ x: 480, y: 64 }], category: "Prototyping", tags: ["checks", "red"] },
  "Prototype Checks: Yellow": { locations: [{ x: 496, y: 64 }], category: "Prototyping", tags: ["checks", "yellow"] },
  "Prototype Ladders: Black": { locations: [{ x: 0, y: 80 }], category: "Prototyping", tags: ["ladder", "black"] },
  "Prototype Ladders: Green": { locations: [{ x: 16, y: 80 }], category: "Prototyping", tags: ["ladder", "green"] },
  "Prototype Ladders: Purple": { locations: [{ x: 32, y: 80 }], category: "Prototyping", tags: ["ladder", "purple"] },
  "Prototype Ladders: Red": { locations: [{ x: 48, y: 80 }], category: "Prototyping", tags: ["ladder", "red"] },
  "Prototype Ladders: Yellow": { locations: [{ x: 64, y: 80 }], category: "Prototyping", tags: ["ladder", "yellow"] },
  "Letter A": { locations: [{ x: 160, y: 64 }], category: "Prototyping", tags: ["letter"] },
  "Letter B": { locations: [{ x: 176, y: 64 }], category: "Prototyping", tags: ["letter"] },
  "Letter C": { locations: [{ x: 192, y: 64 }], category: "Prototyping", tags: ["letter"] },
  "Letter D": { locations: [{ x: 208, y: 64 }], category: "Prototyping", tags: ["letter"] },
  "Letter E": { locations: [{ x: 224, y: 64 }], category: "Prototyping", tags: ["letter"] },
  "Small Crosses: Black": { locations: [{ x: 272, y: 64 }], category: "Prototyping", tags: ["cross", "black"] },
  "Small Crosses: Green": { locations: [{ x: 288, y: 64 }], category: "Prototyping", tags: ["cross", "green"] },
  "Small Crosses: Purple": { locations: [{ x: 304, y: 64 }], category: "Prototyping", tags: ["cross", "purple"] },
  "Small Crosses: Red": { locations: [{ x: 320, y: 64 }], category: "Prototyping", tags: ["cross", "red"] },
  "Small Crosses: Yellow": { locations: [{ x: 336, y: 64 }], category: "Prototyping", tags: ["cross", "yellow"] },

  "Glass": { locations: [{ x: 128, y: 16 }], category: "Misc", tags: ["glass"] },
  "Window": { locations: [{ x: 144, y: 16 }], category: "Misc", tags: ["glass", "window"] },
  "Black and White Checks": { locations: [{ x: 160, y: 16 }], category: "Misc", tags: ["checks"] },
  "Blue Carpet": { locations: [{ x: 176, y: 16 }], category: "Misc", tags: ["carpet", "blue"] },
  "Red Carpet": { locations: [{ x: 176, y: 48 }], category: "Misc", tags: ["carpet", "red"] },
  "Ladder": { locations: [{ x: 416, y: 16 }], category: "Misc", tags: ["ladder"] },
  "Steel Ladder": { locations: [{ x: 432, y: 16 }], category: "Misc", tags: ["ladder", "metal"] },
  "TNT Side": { locations: [{ x: 32, y: 48 }], category: "Misc", tags: ["tnt"] },
  "TNT Top": { locations: [{ x: 48, y: 48 }], category: "Misc", tags: ["tnt"] },
  "TNT Bottom": { locations: [{ x: 64, y: 48 }], category: "Misc", tags: ["tnt"] },
  "Chain": { locations: [{ x: 352, y: 32 }], category: "Industrial", tags: ["chain"] },
  "Chain2": { locations: [{ x: 368, y: 32 }], category: "Industrial", tags: ["chain"] },
  "Rope": { locations: [{ x: 16, y: 48 }], category: "Misc", tags: ["rope"] },
  "Sardine": { locations: [{ x: 240, y: 64 }], category: "Misc", tags: ["animal"] },
  "Crab": { locations: [{ x: 256, y: 64 }], category: "Misc", tags: ["animal"] },
  "Danger Stripes": { locations: [{ x: 176, y: 32 }], category: "Industrial", tags: ["warning"] },
  "Warning Sign": { locations: [{ x: 288, y: 80 }], category: "Industrial", tags: ["warning"] },
  "Small Danger Sign": { locations: [{ x: 160, y: 48 }], category: "Industrial", tags: ["warning"] },
  "Dark Spiral": { locations: [{ x: 160, y: 32 }], category: "Misc", tags: ["pattern"] },
  "Arrow Block": { locations: [{ x: 432, y: 32 }], category: "Misc", tags: ["arrow"] },
  "Striped Pillar Side": { locations: [{ x: 464, y: 32 }], category: "Misc", tags: ["pillar"] },
  "Striped Pillar Top": { locations: [{ x: 480, y: 32 }, { x: 496, y: 32 }], category: "Misc", tags: ["pillar"] },
  "Neutral Diamonds": { locations: [{ x: 112, y: 64 }], category: "Misc", tags: ["pattern"] },
  "Iron Door Top": { locations: [{ x: 480, y: 16 }], category: "Industrial", tags: ["door", "iron"] },
  "Iron Door Bottom": { locations: [{ x: 496, y: 16 }], category: "Industrial", tags: ["door", "iron"] },
  "Copper Squares": { locations: [{ x: 352, y: 48 }], category: "Industrial", tags: ["metal", "pixel"] },
};
